# -*- coding: utf-8 -*-
"""cnnbase

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhtPe-Iy6mIJbmuhmfw7qrNdF5c51izu
"""

import os
import zipfile
import numpy as np
import gdown
import cv2

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import RandomFlip, RandomRotation, RandomBrightness

IMG_SIZE = 64
CHANNELS = 3 # RGB images


def download_dataset(url, arquivo_zip="hand_other.zip"):
    gdown.download(
        url,
        arquivo_zip,
        fuzzy=True,
        quiet=False
    )
    zip_referencia = zipfile.ZipFile(arquivo_zip,'r')
    zip_referencia.extractall(".")
    zip_referencia.close()
    return os.path.join(".", "hand_other")

def extrair_atributos(caminho_imagem):
    img = cv2.imread(caminho_imagem)
    if img is None:
      return None
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img.astype('float32') / 255.0 # Normaliza os pixel para valores entre [0, 1]
    return img

def carregar_dados(caminho_base):
    X = []
    y = []

    # hand = 0
    pasta_hand = os.path.join(caminho_base, "hand")
    for arquivo in os.listdir(pasta_hand):
        if arquivo.lower().endswith(('.png', '.jpg', '.jpeg')):
            caminho_completo = os.path.join(pasta_hand, arquivo)
            atributos = extrair_atributos(caminho_completo)
            if atributos is not None:
                X.append(atributos)
                y.append(0)

    # other = 1
    pasta_other = os.path.join(caminho_base, "other")
    for arquivo in os.listdir(pasta_other):
        if arquivo.lower().endswith(('.png', '.jpg', '.jpeg')):
            caminho_completo = os.path.join(pasta_other, arquivo)
            atributos = extrair_atributos(caminho_completo)
            if atributos is not None:
                X.append(atributos)
                y.append(1)

    X = np.array(X)
    y = np.array(y)
    return X, y

def dividir_dados(X, y, porcentagem_teste, random_state):
  X_treino, X_teste, y_treino, y_teste = train_test_split(
      X,
      y,
      test_size=porcentagem_teste,
      stratify = y, #ponto importante
      random_state=random_state)
  return X_treino, X_teste, y_treino, y_teste


#softmax

def gerar_modelo():
  modelo = Sequential()

  # Permite que o modelo veja a mão girada em qualquer ângulo (360 graus)
  modelo.add(RandomRotation(factor=0.5, fill_mode='nearest', input_shape=(IMG_SIZE, IMG_SIZE, CHANNELS)))

  # Também ajuda muito adicionar o espelhamento horizontal e vertical
  modelo.add(RandomFlip("horizontal_and_vertical"))

  # Bloco 1: Captura de bordas e contornos simples (dedos)
  modelo.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(IMG_SIZE, IMG_SIZE, CHANNELS)))
  modelo.add(MaxPooling2D((2, 2)))

  # Bloco 2: Combinação de bordas em formatos geométricos
  modelo.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
  modelo.add(MaxPooling2D((2, 2)))

  # Bloco 3: Texturas e estruturas complexas (mão aberta vs fechada)
  modelo.add(Conv2D(128, (3, 3), activation='relu', padding='same'))
  modelo.add(MaxPooling2D((2, 2)))

  # Vetorização
  modelo.add(Flatten())

  # Classificador Interno Ajustado (Reduzido para evitar que o modelo decore)
  modelo.add(Dense(64, activation='relu'))
  modelo.add(Dropout(0.4)) # Protege contra overfitting sem apagar o aprendizado

  # Classificador de Saída (Suas duas classes)
  modelo.add(Dense(2, activation='softmax'))

  return modelo

def avaliacao(modelo, X_teste, y_teste):
    y_prob = modelo.predict(X_teste)
    y_prob = np.argmax(y_prob, axis=1)
    acc = accuracy_score(y_teste, y_prob)
    print("Acurácia:", acc)
    print(confusion_matrix(y_teste, y_prob))


# dogs_cats dataset_url = "https://drive.google.com/file/d/1c2K2n8VH69RY1KOXDViJ4lsqpYeCPd4Z/view?usp=sharing"
dataset_url = "https://drive.google.com/file/d/1mJCgcVcD-StvXQcS5gNG2Uokj62zDV2V/view?usp=sharing"
base_dataset_path = download_dataset(dataset_url)
X, y = carregar_dados(base_dataset_path)
X_treino, X_teste, y_treino, y_teste = dividir_dados(X, y, 0.2, 25)
modelo = gerar_modelo()

opt_adam = Adam(learning_rate=0.0001)

modelo.compile(optimizer = opt_adam, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
modelo.fit(X_treino, y_treino, epochs=20, batch_size=32, validation_split=0.1)
modelo.save('identify_open_hands.keras')
avaliacao(modelo, X_teste, y_teste)